[mod]
id = "dice_and_delish"
name = "Dice & Delish"
group = "com.panzer.mods"
package = "com.panzer.mods.dice_and_delish"
version = "1.0.0"
license = "AGPLv3"
resources_license = "CC-BY-NC-SA-4.0"
authors = "Bichal"
description = "A fresh, lightweight cooking and farming expansion adding wild crops, pole-grown tomatoes, grill workstations, and delicious new recipes to Minecraft."
side = "BOTH"
issues = "https://github.com/PanzerDevOrg/DiceAndDelish/issues"
banner = "banner.png"

[stonecutter]
profile = "legacy"
#extra_versions = ["1.21.5"]
exclude_versions = ["1.21.4"]
vcs_version = "1.21.1"

[stonecutter.profiles.legacy]
versions = ["1.21.1", "1.21.3"]

[integrations]
jade_id = "jade"
jade_type = "optional"
jade_ordering = "AFTER"
jade_side = "CLIENT"

jei_id = "jei"
jei_type = "optional"
jei_ordering = "AFTER"
jei_side = "CLIENT"

["1.21.1"]
minecraft_version = "1.21.1"
minecraft_version_range = "[1.21,1.21.2)"
neo_version = "21.1.248"
neo_version_range = "[21.0,21.2)"
parchment_mappings_version = "2024.11.17"

jei_version = "19.43.0.392"
jei_version_range = "[19,20)"
jade_version = "15.1.6+neoforge"
jade_version_range = "[15,16)"

["1.21.3"]
minecraft_version = "1.21.3"
minecraft_version_range = "[1.21.3,1.21.4)"
neo_version = "21.3.97"
neo_version_range = "[21.3,21.4)"
parchment_mappings_version = "2024.12.07"

jei_version = "0" # JEI is not compatible
jei_version_range = "[0,)"
jade_version = "16.0.1+neoforge"
jade_version_range = "[16,17)"

#["1.21.4"]
#minecraft_version = "1.21.4"
#minecraft_version_range = "[1.21.4,1.21.5)"
#neo_version = "21.4.157"
#neo_version_range = "[21.4,21.5)"
#parchment_mappings_version = "2025.03.23"
#
#jei_version = "20.0.0.4"
#jei_version_range = "[20.0,20.1)"
#jade_version = "17.3.0+neoforge"
#jade_version_range = "[17,18)"
